import './globals.css';
import {Inter} from 'next/font/google';
import {Providers} from '@/redux/provider';
import WrapperGraphQl from '@/lib/grahpQl';
const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <WrapperGraphQl>
            <div className="h-full w-full relative">{children}</div>
          </WrapperGraphQl>
        </Providers>
      </body>
    </html>
  );
}
